services:
  - type: web
    name: pdf-to-mcq-backend
    env: python
    rootDir: backend
    buildCommand: bash build.sh
    startCommand: uvicorn index:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: VERCEL_BLOB_READ_WRITE_TOKEN
        sync: false
      - key: VERCEL_BLOB_STORE_ID
        sync: false
      - key: FRONTEND_URL
        sync: false
