services:
  - type: web
    name: pdf-to-mcq-generator-fastapi
    env: docker
    rootDir: backend
    dockerfilePath: ./Dockerfile
    plan: free
    autoDeploy: true
    healthCheckPath: /docs
    envVars:
      - key: FRONTEND_URL
        sync: false
      - key: OPENAI_API_KEY
        sync: false