import { motion } from 'framer-motion';
import { CheckCircle, Download, RefreshCw, ArrowLeft } from 'lucide-react';
import { jsPDF } from 'jspdf';

const MCQResults = ({ mcqs, onGenerateMore, onReset }) => {
  const containerVariants = {
    hidden: { opacity: 0 },
    visible: {
      opacity: 1,
      transition: {
        staggerChildren: 0.1
      }
    }
  };

  const itemVariants = {
    hidden: { y: 20, opacity: 0 },
    visible: {
      y: 0,
      opacity: 1,
      transition: {
        duration: 0.5,
        ease: "easeOut"
      }
    }
  };

  const downloadPDF = () => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 20;
    let yPosition = margin;

    // Title
    doc.setFontSize(20);
    doc.setFont('helvetica', 'bold');
    doc.text('Generated MCQ Questions', pageWidth / 2, yPosition, { align: 'center' });
    yPosition += 15;

    // Questions
    doc.setFontSize(12);
    mcqs.forEach((mcq, index) => {
      // Check if we need a new page
      if (yPosition > pageHeight - 60) {
        doc.addPage();
        yPosition = margin;
      }

      // Question number and text
      doc.setFont('helvetica', 'bold');
      const questionText = `Q${index + 1}. ${mcq.question}`;
      const splitQuestion = doc.splitTextToSize(questionText, pageWidth - 2 * margin);
      doc.text(splitQuestion, margin, yPosition);
      yPosition += 7 * splitQuestion.length;

      // Options
      doc.setFont('helvetica', 'normal');
      const optionsArray = Array.isArray(mcq.options) ? mcq.options : Object.values(mcq.options);
      optionsArray.forEach((option, optIndex) => {
        if (yPosition > pageHeight - 40) {
          doc.addPage();
          yPosition = margin;
        }
        const optionLabel = String.fromCharCode(65 + optIndex);
        const correctAnswer = mcq.answer || mcq.correct_answer;
        const isCorrect = correctAnswer === optionLabel || correctAnswer === option;
        if (isCorrect) {
          doc.setFont('helvetica', 'bold');
          doc.setTextColor(0, 128, 0);
        } else {
          doc.setFont('helvetica', 'normal');
          doc.setTextColor(0, 0, 0);
        }
        const optionText = `   ${optionLabel}. ${option}`;
        const splitOption = doc.splitTextToSize(optionText, pageWidth - 2 * margin - 10);
        doc.text(splitOption, margin, yPosition);
        yPosition += 7 * splitOption.length;
      });

      doc.setTextColor(0, 0, 0);
      yPosition += 8;
    });

    // Footer
    const totalPages = doc.internal.pages.length - 1;
    for (let i = 1; i <= totalPages; i++) {
      doc.setPage(i);
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.text(
        `Generated by PDF2MCQ | Page ${i} of ${totalPages}`,
        pageWidth / 2,
        pageHeight - 10,
        { align: 'center' }
      );
    }

    doc.save('mcq-questions.pdf');
  };

  return (
    <section className="py-20 px-4">
      <div className="max-w-4xl mx-auto">
        {/* Header */}
        <motion.div
          initial={{ opacity: 0, y: -20 }}
          animate={{ opacity: 1, y: 0 }}
          className="text-center mb-12"
        >
          <div className="flex items-center justify-center mb-4">
            <CheckCircle className="w-12 h-12 text-green-400" />
          </div>
          <h2 className="text-3xl md:text-4xl font-bold mb-4 text-gradient">
            Answer Key - All Correct Answers
          </h2>
          <p className="text-gray-400 mb-6">
            {mcqs.length} {mcqs.length === 1 ? 'question' : 'questions'} with answers shown
          </p>

          {/* Action Buttons */}
          <div className="flex flex-wrap items-center justify-center gap-4">
            {/* Secondary: Download PDF */}
            <motion.button
              onClick={downloadPDF}
              className="flex items-center space-x-2 px-6 py-3 rounded-xl glass border border-green-500/40 text-white font-semibold hover:bg-green-500/20 hover:border-green-500/60 transition-all"
              whileHover={{ scale: 1.05 }}
              whileTap={{ scale: 0.95 }}
            >
              <Download className="w-5 h-5 text-green-400" />
              <span>Download PDF</span>
            </motion.button>

            {/* Secondary: Generate More */}
            <motion.button
              onClick={onGenerateMore}
              className="flex items-center space-x-2 px-6 py-3 rounded-xl glass border border-indigo-500/40 text-white font-semibold hover:bg-indigo-500/20 hover:border-indigo-500/60 transition-all"
              whileHover={{ scale: 1.05 }}
              whileTap={{ scale: 0.95 }}
            >
              <RefreshCw className="w-5 h-5 text-indigo-400" />
              <span>Generate More</span>
            </motion.button>

            {/* Tertiary: New PDF */}
            <motion.button
              onClick={onReset}
              className="flex items-center space-x-2 px-6 py-3 rounded-xl glass border border-white/10 text-gray-400 font-semibold hover:bg-white/5 hover:border-white/20 hover:text-white transition-all"
              whileHover={{ scale: 1.02 }}
              whileTap={{ scale: 0.98 }}
            >
              <ArrowLeft className="w-5 h-5" />
              <span>New PDF</span>
            </motion.button>
          </div>
        </motion.div>

        {/* MCQ Cards */}
        <motion.div
          variants={containerVariants}
          initial="hidden"
          animate="visible"
          className="space-y-6"
        >
          {mcqs.map((mcq, index) => (
            <motion.div
              key={index}
              variants={itemVariants}
              className="glass rounded-2xl p-4 sm:p-6 border border-white/10 hover:border-indigo-400/30 transition-all group"
              whileHover={{ y: -5 }}
            >
              {/* Question */}
              <div className="mb-4">
                <span className="inline-block px-3 py-1 rounded-lg bg-indigo-500/20 text-indigo-300 text-sm font-semibold mb-3">
                  Question {index + 1}
                </span>
                <h3 className="text-lg sm:text-xl font-semibold text-white">
                  {mcq.question}
                </h3>
              </div>

              {/* Options */}
              <div className="space-y-3">
                {(Array.isArray(mcq.options) ? mcq.options : Object.entries(mcq.options)).map((item, optIndex) => {
                  // Handle both array format ["opt1", "opt2"] and object format {"A": "opt1", "B": "opt2"}
                  const optionLabel = Array.isArray(mcq.options) 
                    ? String.fromCharCode(65 + optIndex) // A, B, C, D for array
                    : item[0]; // Use key from object
                  const option = Array.isArray(mcq.options) ? item : item[1];
                  
                  const correctAnswer = mcq.answer || mcq.correct_answer;
                  const isCorrect = correctAnswer === optionLabel || correctAnswer === option;

                  return (
                    <motion.div
                      key={optIndex}
                      className={`flex items-start space-x-3 p-4 rounded-xl transition-all ${
                        isCorrect
                          ? 'bg-green-500/10 border-2 border-green-400/50'
                          : 'bg-white/5 border border-white/10'
                      }`}
                      whileHover={{ x: 5 }}
                    >
                      <span
                        className={`flex-shrink-0 w-8 h-8 rounded-lg flex items-center justify-center font-bold text-sm ${
                          isCorrect
                            ? 'bg-green-500/20 text-green-300'
                            : 'bg-white/10 text-gray-400'
                        }`}
                      >
                        {optionLabel}
                      </span>
                      <p className={`flex-1 ${isCorrect ? 'text-green-100 font-medium' : 'text-gray-300'}`}>
                        {option}
                      </p>
                      {isCorrect && (
                        <CheckCircle className="w-5 h-5 text-green-400 flex-shrink-0" />
                      )}
                    </motion.div>
                  );
                })}
              </div>
            </motion.div>
          ))}
        </motion.div>

        {/* Action Buttons - Bottom */}
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.5 }}
          className="mt-8 sm:mt-12 text-center px-4"
        >
          {/* Action Buttons */}
          <div className="flex flex-col sm:flex-row flex-wrap items-center justify-center gap-3 sm:gap-4">
            {/* Secondary: Download PDF */}
            <motion.button
              onClick={downloadPDF}
              className="w-full sm:w-auto flex items-center justify-center space-x-2 px-5 sm:px-6 py-2.5 sm:py-3 rounded-xl glass border border-green-500/40 text-white font-semibold hover:bg-green-500/20 hover:border-green-500/60 transition-all text-sm sm:text-base"
              whileHover={{ scale: 1.05 }}
              whileTap={{ scale: 0.95 }}
            >
              <Download className="w-4 h-4 sm:w-5 sm:h-5 text-green-400" />
              <span>Download PDF</span>
            </motion.button>

            {/* Secondary: Generate More */}
            <motion.button
              onClick={onGenerateMore}
              className="w-full sm:w-auto flex items-center justify-center space-x-2 px-5 sm:px-6 py-2.5 sm:py-3 rounded-xl glass border border-indigo-500/40 text-white font-semibold hover:bg-indigo-500/20 hover:border-indigo-500/60 transition-all text-sm sm:text-base"
              whileHover={{ scale: 1.05 }}
              whileTap={{ scale: 0.95 }}
            >
              <RefreshCw className="w-4 h-4 sm:w-5 sm:h-5 text-indigo-400" />
              <span>Generate More</span>
            </motion.button>

            {/* Tertiary: New PDF */}
            <motion.button
              onClick={onReset}
              className="w-full sm:w-auto flex items-center justify-center space-x-2 px-5 sm:px-6 py-2.5 sm:py-3 rounded-xl glass border border-white/10 text-gray-400 font-semibold hover:bg-white/5 hover:border-white/20 hover:text-white transition-all text-sm sm:text-base"
              whileHover={{ scale: 1.02 }}
              whileTap={{ scale: 0.98 }}
            >
              <ArrowLeft className="w-4 h-4 sm:w-5 sm:h-5" />
              <span>New PDF</span>
            </motion.button>
          </div>
        </motion.div>
      </div>
    </section>
  );
};

export default MCQResults;
